# Generated by Django 3.0.7 on 2020-12-30 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201230_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileimage',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
